### ISSUE TITLE
Support for breaking changes introduced by new opentelemetry-js version

### ISSUE THREAD

**Issue by adrianmxb** [marcbachmann/opentelemetry-node-metrics#2]
Hello,

open-telemetry recently updated opentelemetry-js some parts of their spec which seems to break this module and in turn also nestjs-otel (see: pragmaticivan/nestjs-otel#151)
More info on this in https://github.com/open-telemetry/opentelemetry-js#upgrade-guidelines

**Comment by marcbachmann** [comment]
Thanks for the hint 👍 
I might try to fix it in the next few days. But PRs are also welcome.

**Comment by marcbachmann** [comment]
#3
